"""find_automatched_accounts.py

Fetch current GL accounts and compare to a provided COA payload to identify
accounts that were automatched (i.e., existing in Ramp prior to the most
recent accounting connection creation/link time).

Usage:
    python -m ERP_Config.find_automatched_accounts --payload ERP_Config/chartOfAccounts_ramp_payload.json

Outputs a list of automatched accounts to stdout.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from datetime import datetime

from utils import load_env
from ramp_client import RampClient
import difflib


def main(argv=None):
    p = argparse.ArgumentParser(description='Find automatched GL accounts')
    p.add_argument('--payload', '-p', required=True, help='Path to Ramp payload JSON (generated by coa_transform)')
    args = p.parse_args(argv)

    payload_path = Path(args.payload)
    if not payload_path.exists():
        print('ERROR: payload not found:', payload_path)
        return 2

    payload = json.loads(payload_path.read_text(encoding='utf-8'))
    accounts = payload.get('accounts') or payload.get('gl_accounts') or []
    input_codes = set()
    for a in accounts:
        code = a.get('account_number') or a.get('external_id') or a.get('code') or a.get('id')
        if code:
            input_codes.add(str(code))

    env = load_env()
    # Load config
    try:
        import tomllib
        cfg = tomllib.loads(Path('config.toml').read_text())
    except Exception:
        cfg = {}

    base_url = cfg.get('ramp', {}).get('base_url')
    token_url = cfg.get('ramp', {}).get('token_url', '')

    client = RampClient(base_url=base_url, token_url=token_url, client_id=env['RAMP_CLIENT_ID'], client_secret=env['RAMP_CLIENT_SECRET'])
    client.authenticate()

    # Fetch accounting connection to get last_linked_at
    base = client.base_url.rstrip('/')
    from urllib.parse import urljoin
    if 'developer/v1' in base:
        conn_ep = urljoin(base + '/', 'accounting/connection')
    else:
        conn_ep = urljoin(base + '/', 'developer/v1/accounting/connection')

    resp = client.session.get(conn_ep)
    resp.raise_for_status()
    conn = resp.json()
    last_linked = conn.get('last_linked_at') or conn.get('created_at')
    if not last_linked:
        print('Could not determine connection timestamp; abort')
        return 3
    conn_ts = datetime.fromisoformat(last_linked)
    print('Connection last_linked_at:', conn_ts.isoformat())

    # Fetch all GL accounts (paginated)
    accounts_data = client._get_paginated_data('accounting/accounts', page_size=100)

    # Build lookup by code, id, and name
    by_code = {}
    by_id = {}
    by_name = {}
    for a in accounts_data:
        code = a.get('code')
        aid = a.get('id')
        name = a.get('name')
        if code:
            by_code[str(code)] = a
        if aid:
            by_id[str(aid)] = a
        if name:
            by_name[str(name).strip().lower()] = a

    # Find matching input codes in existing accounts
    automatched_by_time = []
    provider_mismatch = []
    fuzzy_matches = []

    # Build a searchable list of existing account names for fuzzy matching
    existing_names = [(a.get('name') or '').strip() for a in accounts_data if a.get('name')]

    for code in sorted(input_codes):
        found = None
        if code in by_code:
            found = by_code[code]
        elif code in by_id:
            found = by_id[code]
        else:
            # no match found for this code; we'll consider fuzzy name matching later
            found = None

        if found:
            created = found.get('created_at')
            if created:
                try:
                    c_ts = datetime.fromisoformat(created)
                except Exception:
                    c_ts = None
            else:
                c_ts = None
            if c_ts and c_ts < conn_ts:
                automatched_by_time.append({'code': code, 'name': found.get('name'), 'ramp_id': found.get('ramp_id'), 'created_at': created, 'provider_name': found.get('provider_name')})
                continue

            # also consider provider mismatch: if the existing account's provider_name is not our provider
            provider = found.get('provider_name')
            if provider and provider != (payload.get('remote_provider_name') or 'ACCOUNTING_SEED'):
                provider_mismatch.append({'code': code, 'name': found.get('name'), 'ramp_id': found.get('ramp_id'), 'provider_name': provider})
            continue

        # If no exact code/id match, attempt exact name match
        name_key = None
        for pa in accounts:
            potential_code = (pa.get('account_number') or pa.get('external_id') or pa.get('code') or pa.get('id'))
            if str(potential_code) == code:
                name_key = (pa.get('account_name') or pa.get('name') or '').strip()
                break

        if name_key:
            lower = name_key.lower()
            if lower in by_name:
                existing = by_name[lower]
                existing_created = existing.get('created_at')
                if existing_created:
                    try:
                        ex_ts = datetime.fromisoformat(existing_created)
                    except Exception:
                        ex_ts = None
                else:
                    ex_ts = None
                if ex_ts and ex_ts < conn_ts:
                    automatched_by_time.append({'code': code, 'name': existing.get('name'), 'ramp_id': existing.get('ramp_id'), 'created_at': existing_created, 'provider_name': existing.get('provider_name'), 'match_type': 'name'})
                    continue

        # Fallback: fuzzy name match against all existing names
        if name_key:
            best = difflib.get_close_matches(name_key, existing_names, n=3, cutoff=0.80)
            if best:
                fuzzy_matches.append({'code': code, 'name': name_key, 'matches': best})

    print(f'Found {len(automatched_by_time)} automatched accounts by timestamp')
    for a in automatched_by_time:
        print(json.dumps(a, ensure_ascii=False))

    print(f'Found {len(provider_mismatch)} accounts where provider_name differs')
    for a in provider_mismatch:
        print(json.dumps(a, ensure_ascii=False))

    print(f'Found {len(fuzzy_matches)} fuzzy name match candidates (cutoff 0.80)')
    for a in fuzzy_matches:
        print(json.dumps(a, ensure_ascii=False))

    print(f'Found {len(automatched_by_time)} automatched accounts by timestamp')
    for a in automatched_by_time:
        print(json.dumps(a, ensure_ascii=False))

    print(f'Found {len(provider_mismatch)} accounts where provider_name differs')
    for a in provider_mismatch:
        print(json.dumps(a, ensure_ascii=False))

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
