"""find_conflicting_gl_accounts.py

Fetch existing Ramp GL accounts and compare to provided COA payload.
Reports conflicts where payload 'id' (external_id/account_number) or 'code'
matches an existing Ramp GL account.

Usage:
  python -m ERP_Config.find_conflicting_gl_accounts --payload ERP_Config/chartOfAccounts_ramp_payload.json
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from typing import List, Dict

from utils import load_env
from ramp_client import RampClient


def main(argv=None):
    p = argparse.ArgumentParser(description='Find GL accounts conflicts by id or code')
    p.add_argument('--payload', '-p', required=True, help='Path to Ramp payload JSON (generated by coa_transform)')
    args = p.parse_args(argv)

    payload_path = Path(args.payload)
    if not payload_path.exists():
        print('ERROR: payload not found:', payload_path)
        return 2

    payload = json.loads(payload_path.read_text(encoding='utf-8'))
    accounts = payload.get('accounts') or payload.get('gl_accounts') or []

    # Build map from payload by external id and by code
    payload_by_id = {}
    payload_by_code = {}

    for a in accounts:
        ext_id = a.get('external_id') or a.get('account_number') or a.get('id')
        code = a.get('account_number') or a.get('code') or a.get('external_id') or a.get('id')
        key_id = str(ext_id).strip() if ext_id is not None else None
        key_code = str(code).strip() if code is not None else None
        if key_id:
            payload_by_id[key_id] = a
        if key_code:
            payload_by_code[key_code] = a

    env = load_env()
    # Load config
    try:
        import tomllib
        cfg = tomllib.loads(Path('config.toml').read_text())
    except Exception:
        cfg = {}

    base_url = cfg.get('ramp', {}).get('base_url')
    token_url = cfg.get('ramp', {}).get('token_url', '')

    client = RampClient(base_url=base_url, token_url=token_url, client_id=env['RAMP_CLIENT_ID'], client_secret=env['RAMP_CLIENT_SECRET'])
    client.authenticate()

    # Fetch all GL accounts
    print('Fetching existing GL accounts from Ramp...')
    existing = client._get_paginated_data('accounting/accounts', page_size=100)

    existing_by_id = {}
    existing_by_code = {}
    for e in existing:
        eid = e.get('id')
        code = e.get('code')
        if eid:
            existing_by_id[str(eid)] = e
        if code:
            existing_by_code[str(code)] = e

    conflicts_by_id: List[Dict] = []
    conflicts_by_code: List[Dict] = []

    # Check id conflicts
    for pid, pa in payload_by_id.items():
        if pid in existing_by_id:
            e = existing_by_id[pid]
            conflicts_by_id.append({
                'payload_id': pid,
                'payload_name': pa.get('account_name') or pa.get('name'),
                'existing_ramp_id': e.get('ramp_id'),
                'existing_name': e.get('name'),
                'existing_code': e.get('code'),
                'existing_provider': e.get('provider_name'),
                'existing_created_at': e.get('created_at')
            })

    # Check code conflicts (if not already matched by id)
    for pcode, pa in payload_by_code.items():
        # skip if id already matched the same object
        if (pa.get('external_id') and str(pa.get('external_id')) in existing_by_id) or (pa.get('account_number') and str(pa.get('account_number')) in existing_by_id):
            continue
        if pcode in existing_by_code:
            e = existing_by_code[pcode]
            conflicts_by_code.append({
                'payload_code': pcode,
                'payload_name': pa.get('account_name') or pa.get('name'),
                'existing_ramp_id': e.get('ramp_id'),
                'existing_name': e.get('name'),
                'existing_code': e.get('code'),
                'existing_provider': e.get('provider_name'),
                'existing_created_at': e.get('created_at')
            })

    print(f"Found {len(conflicts_by_id)} conflicts by external id and {len(conflicts_by_code)} conflicts by code")
    if conflicts_by_id:
        print('\nConflicts by external id:')
        for c in conflicts_by_id:
            print(json.dumps(c, ensure_ascii=False))
    if conflicts_by_code:
        print('\nConflicts by code:')
        for c in conflicts_by_code:
            print(json.dumps(c, ensure_ascii=False))

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
