"""patch_conflicting_gl_accounts.py

Prepare and optionally apply PATCH updates to existing Ramp GL accounts that
conflict with your payload (by external id). Default behavior is a dry-run that
prints planned changes; pass --apply to perform live PATCH calls.

Usage:
  python -m ERP_Config.patch_conflicting_gl_accounts --payload ERP_Config/chartOfAccounts_ramp_payload.json
  python -m ERP_Config.patch_conflicting_gl_accounts --payload ... --apply
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from typing import Dict, List

from utils import load_env
from ramp_client import RampClient


def main(argv=None):
    p = argparse.ArgumentParser(description='PATCH conflicting Ramp GL accounts to match payload')
    p.add_argument('--payload', '-p', required=True, help='Path to Ramp payload JSON (generated by coa_transform)')
    p.add_argument('--apply', action='store_true', help='Perform live PATCH requests (destructive)')
    args = p.parse_args(argv)

    payload_path = Path(args.payload)
    if not payload_path.exists():
        print('ERROR: payload not found:', payload_path)
        return 2

    payload = json.loads(payload_path.read_text(encoding='utf-8'))
    accounts = payload.get('accounts') or payload.get('gl_accounts') or []

    # Build map from payload by external id
    payload_by_id: Dict[str, Dict] = {}
    for a in accounts:
        ext_id = a.get('external_id') or a.get('account_number') or a.get('id')
        if ext_id is not None:
            payload_by_id[str(ext_id).strip()] = a

    env = load_env()
    # Load config
    try:
        import tomllib
        cfg = tomllib.loads(Path('config.toml').read_text())
    except Exception:
        cfg = {}

    base_url = cfg.get('ramp', {}).get('base_url')
    token_url = cfg.get('ramp', {}).get('token_url', '')

    client = RampClient(base_url=base_url, token_url=token_url, client_id=env['RAMP_CLIENT_ID'], client_secret=env['RAMP_CLIENT_SECRET'])
    client.authenticate()

    # Fetch existing GL accounts
    print('Fetching existing GL accounts from Ramp...')
    existing = client._get_paginated_data('accounting/accounts', page_size=100)

    existing_by_id = {}
    for e in existing:
        eid = e.get('id')
        if eid:
            existing_by_id[str(eid)] = e

    # Build patch plan
    patch_plan: List[Dict] = []
    for pid, pa in payload_by_id.items():
        if pid not in existing_by_id:
            continue
        e = existing_by_id[pid]
        ramp_id = e.get('ramp_id')
        if not ramp_id:
            # can't patch without ramp_id
            continue
        desired_name = pa.get('account_name') or pa.get('name')
        desired_code = pa.get('account_number') or pa.get('code') or pa.get('external_id') or pa.get('id')
        updates = {}
        if desired_name and desired_name != e.get('name'):
            updates['name'] = desired_name
        if desired_code is not None and str(desired_code) != (e.get('code') or ''):
            updates['code'] = str(desired_code)
        if updates:
            patch_plan.append({'external_id': pid, 'ramp_id': ramp_id, 'existing_name': e.get('name'), 'existing_code': e.get('code'), 'updates': updates})

    print(f'Planned {len(patch_plan)} patches')
    for p in patch_plan:
        print(json.dumps(p, ensure_ascii=False))

    if not patch_plan:
        print('No changes to apply.')
        return 0

    if not args.apply:
        print('\nDry-run complete. Re-run with --apply to perform live PATCH updates.')
        return 0

    # Apply patches
    results = []
    from urllib.parse import urljoin
    base = client.base_url.rstrip('/')
    if 'developer/v1' in base:
        endpoint_base = urljoin(base + '/', 'accounting/accounts/')
    else:
        endpoint_base = urljoin(base + '/', 'developer/v1/accounting/accounts/')

    for item in patch_plan:
        rid = item['ramp_id']
        url = endpoint_base + str(rid)
        body = item['updates']
        try:
            resp = client.session.patch(url, json=body, timeout=30)
            status = resp.status_code
            try:
                data = resp.json()
            except Exception:
                data = resp.text
            ok = (200 <= status < 300)
            results.append({'ramp_id': rid, 'ok': ok, 'status': status, 'response': data, 'updates': body})
        except Exception as ex:
            results.append({'ramp_id': rid, 'ok': False, 'error': str(ex), 'updates': body})

    successes = sum(1 for r in results if r.get('ok'))
    failures = len(results) - successes
    print(f'PATCH complete: {successes} succeeded, {failures} failed')
    for r in results:
        print(json.dumps(r, ensure_ascii=False))

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
