"""upload_remaining_gl_accounts.py

Filter out GL accounts that already exist in Ramp (by external id) and upload the
remaining accounts in batches. Default is dry-run; pass --apply to perform live upload.

Usage:
  python -m ERP_Config.upload_remaining_gl_accounts --payload ERP_Config/chartOfAccounts_ramp_payload.json
  python -m ERP_Config.upload_remaining_gl_accounts --payload ... --apply
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from typing import List

from utils import load_env
from ramp_client import RampClient


def main(argv=None):
    p = argparse.ArgumentParser(description='Upload remaining GL accounts after skipping existing ones')
    p.add_argument('--payload', '-p', required=True, help='Path to Ramp payload JSON (generated by coa_transform)')
    p.add_argument('--apply', action='store_true', help='Perform live upload (destructive)')
    p.add_argument('--incremental', action='store_true', help='When applying, upload accounts one-by-one to isolate conflicts')
    args = p.parse_args(argv)

    payload_path = Path(args.payload)
    if not payload_path.exists():
        print('ERROR: payload not found:', payload_path)
        return 2

    payload = json.loads(payload_path.read_text(encoding='utf-8'))
    accounts = payload.get('accounts') or payload.get('gl_accounts') or []

    env = load_env()
    try:
        import tomllib
        cfg = tomllib.loads(Path('config.toml').read_text())
    except Exception:
        cfg = {}

    client = RampClient(base_url=cfg.get('ramp', {}).get('base_url'), token_url=cfg.get('ramp', {}).get('token_url',''), client_id=env['RAMP_CLIENT_ID'], client_secret=env['RAMP_CLIENT_SECRET'])
    client.authenticate()

    # Fetch existing GL accounts ids
    existing = client._get_paginated_data('accounting/accounts', page_size=100)
    existing_ids = set(str(e.get('id')) for e in existing if e.get('id'))

    # Build list of accounts to upload (skip those whose external id/account_number exists)
    to_upload = []
    skipped = []
    for a in accounts:
        ext_id = a.get('external_id') or a.get('account_number') or a.get('id')
        key = str(ext_id) if ext_id is not None else None
        if key and key in existing_ids:
            skipped.append(key)
            continue
        to_upload.append({
            'classification': a.get('account_type'),
            'code': a.get('account_number') or a.get('external_id') or a.get('code'),
            'id': a.get('external_id') or a.get('account_number') or a.get('id'),
            'name': a.get('account_name') or a.get('name')
        })

    print(f'Total accounts in payload: {len(accounts)}')
    print(f'Skipped (existing) accounts: {len(skipped)}')
    print(f'Accounts to upload: {len(to_upload)}')

    if not to_upload:
        print('Nothing to upload.')
        return 0

    # If not applying, just dry-run the full batch
    if not args.apply:
        ok, results = client.upload_gl_accounts(to_upload, dry_run=True)
        print('Dry-run upload result:', ok)
        print(results)
        return 0

    # Apply mode
    if args.incremental:
        print('Incremental apply: uploading accounts one-by-one to isolate conflicts')
        successes = []
        failures = []
        for a in to_upload:
            ok, res = client.upload_gl_accounts([a], dry_run=False, batch_size=1)
            # res is a list with single batch result
            r = res[0] if isinstance(res, list) and res else res
            if ok:
                successes.append({'code': a.get('code'), 'id': a.get('id'), 'response': r})
                print('Uploaded:', a.get('id') or a.get('code'))
            else:
                failures.append({'code': a.get('code'), 'id': a.get('id'), 'response': r})
                print('Failed to upload:', a.get('id') or a.get('code'), '->', r)
        print(f'Incremental upload complete: {len(successes)} succeeded, {len(failures)} failed')
        if failures:
            print('Failures (first 10 shown):')
            for f in failures[:10]:
                print(f)
        return 0
    else:
        # Bulk apply
        ok, results = client.upload_gl_accounts(to_upload, dry_run=False)
        print('Bulk upload result:', ok)
        print(results)
        return 0


if __name__ == '__main__':
    raise SystemExit(main())
